return {
        -- t_Co=256,
		relativenumber = true,
        number = true,
        cursorline = true,
        cursorcolumn = true,
        showmode = true,
        showcmd = true,
        mouse = a,
        autoindent = true,
        tabstop = 2,
        shiftwidth = 4,
        expandtab = true,
        textwidth = 80,
        wrap = true,
        linebreak = true,
        wrapmargin = 2,
        scrolloff = 5,
        sidescrolloff = 15,
        laststatus = 2,
        ruler = true,
        showmatch = true,
        showtabline = 2,
        hlsearch = true,
        ignorecase = true,
        -- nobackup = true,
        -- noswapfile = true,
        encoding = "utf-8",
        -- listchars="tab:>-,space:▯",
        listchars="tab:>-,space:⋅,eol:↴",
        -- "tab:»·,nbsp:+,trail:·,extends:→,precedes:←",
        -- list = true
        -- backupdir="~/.local/.vim/.backup//",
        autochdir = true,
        autoread = true,
        wildmenu = true,
        background = "dark",
        timeout = true,
        ttimeout = true,
        timeoutlen = 500,
        ttimeoutlen = 0,
        termguicolors=true,
        -- fillchars = "vert:\\|,eob:\\",
        gcr = [[n-v-c:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor,]]..
              [[ve:ver35-Cursor,]]..
              [[o:hor50-Cursor,]]..
              [[i-ci:ver25-Cursor/lCursor,]]..
              [[r:hor50-Cursor/lCursor]],
        completeopt = 'menuone,noinsert',
        -- noswapfile = true,
        -- nobackup = true,


	}
